### ISSUE TITLE
Error in cltorch tests

### ISSUE THREAD

**Issue by AlbertoSabater** [hughperkins/distro#3]
I have installed this distro-cl in a Ubuntu 16.04. The installation was successful, but I have an error executing cl tests:

```
luajit -l cltorch -e 'cltorch.test()'

running tests...
aftter requiring cltorch.unit_storage
Running 2 tests
|_  ==> test_basic
Using Mesa , OpenCL platform: Clover
Using OpenCL device: AMD JUNIPER (DRM 2.43.0, LLVM 3.8.0)
Segmentation fault (core dumped)
```

Similar error appear with clnn test.

Can it be a problem with opencl drivers or with my GPU (ATI Radeon 5770)?

**Comment by hughperkins** [comment]
Hmmm. I'm gonna go with it's probably a Clover issue.... but .... we can try digging a bit.  How's your `gdb` skills?  Can you do the following please?

```
sudo apt-get install -y gdb
cat >rungdb.sh <<EOF
#!/bin/bash

gdb $1 -ex "catch throw" -ex "run $2 $3 $4 $5 $6 $7 $8 $9"
EOF
chmod +x rungdb.sh
cat >/tmp/test.lua <<EOF
require 'cltorch'
cltorch.test()
EOF
./rungdb.sh luajit /tmp/test.lua
```

When it segfaults, type `bt`, and copy/paste the output.  At least, the first 10-20 lines of the output, meaning the first 10-15 frames or so.

I'm not sure where we'll go from there, but it might shed some light.

By the way, Clover is a bit ... not entirely compliant with OpenCL 1.1 or OpenCL 1.2, as far as I know.  For example, it doesnt implement `tanh`.  It's quite possible that even if you solve this particulr problem, then there'll be another 10-20 problems to surmount.  How enthusiastic are you about solving these issues and getting them working?  It will need quite a lot of dedication, time, and technical skills on your own part.

Otherwise, if you want something that works, now, you might consider installing the proprietary AMD binary blob driver :-)
